import * as fs from 'fs/promises';
import * as path from 'path';
import { execSync } from 'child_process';

/**
 * Check if current directory is a Git repository
 */
export const isGitRepository = async (cwd: string = process.cwd()): Promise<boolean> => {
    try {
        execSync('git rev-parse --git-dir', { cwd, stdio: 'ignore' });
        return true;
    } catch {
        return false;
    }
};

/**
 * Get the .git directory path
 */
export const getGitDir = (cwd: string = process.cwd()): string => {
    try {
        const gitDir = execSync('git rev-parse --git-dir', { cwd, encoding: 'utf-8' }).trim();
        return path.isAbsolute(gitDir) ? gitDir : path.join(cwd, gitDir);
    } catch {
        throw new Error('Not a git repository');
    }
};

/**
 * Install the prepare-commit-msg hook
 */
export const installHook = async (cwd: string = process.cwd()): Promise<void> => {
    const gitDir = getGitDir(cwd);
    const hooksDir = path.join(gitDir, 'hooks');
    const hookPath = path.join(hooksDir, 'prepare-commit-msg');

    // Ensure hooks directory exists
    await fs.mkdir(hooksDir, { recursive: true });

    // Create the hook script
    const hookScript = `#!/usr/bin/env node

// Auto-generated by api-diff-logger
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const COMMIT_MSG_FILE = process.argv[2];
const COMMIT_SOURCE = process.argv[3];

// Only run for regular commits (not merge, squash, etc.)
if (COMMIT_SOURCE) {
  process.exit(0);
}

(async () => {
  try {
    // Read the commit message
    const commitMsg = fs.readFileSync(COMMIT_MSG_FILE, 'utf-8');
    
    // Load config to get hook prefix
    const configPath = path.join(process.cwd(), 'node_modules', 'api-diff-logger', 'dist', 'config.js');
    const { loadConfig } = require(configPath);
    
    const config = await loadConfig();
    const prefix = config.hookPrefix || '[api]';
    
    // Check if commit message starts with the API prefix
    if (!commitMsg.trim().startsWith(prefix)) {
      process.exit(0);
    }
    
    console.log('🔍 API prefix detected, generating changelog...');
    
    // Get the current HEAD commit
    let fromCommit = 'HEAD';
    try {
      execSync('git rev-parse HEAD', { stdio: 'ignore' });
    } catch {
      // No commits yet, compare with empty tree
      fromCommit = '4b825dc642cb6eb9a060e54bf8d69288fbee4904';
    }
    
    // Run the changelog generator comparing staged changes with HEAD
    const cliPath = path.join(process.cwd(), 'node_modules', 'api-diff-logger', 'dist', 'cli.js');
    
    try {
      const output = execSync(
        \`node "\${cliPath}" generate --from \${fromCommit} --to HEAD\`,
        { encoding: 'utf-8', stdio: 'pipe' }
      );
      
      console.log(output);
      
      // If configured, append changelog summary to commit message
      if (config.appendToCommitMessage) {
        const changelogPath = path.join(process.cwd(), config.outputPath || 'API_CHANGELOG.md');
        if (fs.existsSync(changelogPath)) {
          const changelog = fs.readFileSync(changelogPath, 'utf-8');
          
          // Extract summary from changelog
          const summaryMatch = changelog.match(/## Summary[\\s\\S]*?(?=##|$)/);
          if (summaryMatch) {
            const summary = summaryMatch[0].trim();
            const updatedMsg = commitMsg.trim() + '\\n\\n' + summary;
            fs.writeFileSync(COMMIT_MSG_FILE, updatedMsg);
          }
        }
      }
      
      // Stage the changelog file
      const changelogFile = config.outputPath || 'API_CHANGELOG.md';
      execSync(\`git add "\${changelogFile}"\`, { stdio: 'inherit' });
      
    } catch (error) {
      console.error('Failed to generate changelog:', error.message);
      // Don't fail the commit, just warn
    }
    
  } catch (error) {
    console.error('Hook error:', error);
    // Don't fail the commit
    process.exit(0);
  }
})();
`;

    // Write the hook script
    await fs.writeFile(hookPath, hookScript, { mode: 0o755 });

    console.log('✅ Git hook installed successfully!');
};

/**
 * Uninstall the prepare-commit-msg hook
 */
export const uninstallHook = async (cwd: string = process.cwd()): Promise<void> => {
    const gitDir = getGitDir(cwd);
    const hookPath = path.join(gitDir, 'hooks', 'prepare-commit-msg');

    try {
        const content = await fs.readFile(hookPath, 'utf-8');

        // Only remove if it's our hook
        if (content.includes('Auto-generated by api-diff-logger')) {
            await fs.unlink(hookPath);
            console.log('✅ Git hook uninstalled successfully!');
        } else {
            console.warn('⚠️  Hook exists but was not created by api-diff-logger. Skipping removal.');
        }
    } catch (error: any) {
        if (error.code === 'ENOENT') {
            console.log('ℹ️  No hook found to uninstall.');
        } else {
            throw error;
        }
    }
};

/**
 * Check if the hook is installed
 */
export const isHookInstalled = async (cwd: string = process.cwd()): Promise<boolean> => {
    try {
        const gitDir = getGitDir(cwd);
        const hookPath = path.join(gitDir, 'hooks', 'prepare-commit-msg');
        const content = await fs.readFile(hookPath, 'utf-8');
        return content.includes('Auto-generated by api-diff-logger');
    } catch {
        return false;
    }
};
